CC = gcc
CFLAGS = -Wall -Wextra -std=c99

run1:
	$(CC) $(CFLAGS) question1/student.c question1/tests.c -o q1
	./q1

run2:
	$(CC) $(CFLAGS) question2/student.c question2/tests.c -o q2
	./q2

run3:
	$(CC) $(CFLAGS) question3/student.c question3/tests.c -o q3
	./q3

clean:
	rm -f q1 q2 q3